### ISSUE TITLE
Cannot install ValueError: --enable-jpeg requested but jpeg not found, aborting.

### ISSUE THREAD

**Issue by alexellis** [pimoroni/scroll-phat#12]
Hi... I bought this item from you at PiWars and you said to let you know if there were any issues. It's all soldered up now and connected but the software would not install for me. Please advise.

Alex

```
[x@zero library]$ sudo python2 ./setup.py  install
running install
running bdist_egg
running egg_info
writing requirements to scrollphat.egg-info/requires.txt
writing scrollphat.egg-info/PKG-INFO
writing top-level names to scrollphat.egg-info/top_level.txt
writing dependency_links to scrollphat.egg-info/dependency_links.txt
reading manifest file 'scrollphat.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'scrollphat.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv6l/egg
running install_lib
running build_py
creating build/bdist.linux-armv6l/egg
copying build/lib/scrollphat.py -> build/bdist.linux-armv6l/egg
byte-compiling build/bdist.linux-armv6l/egg/scrollphat.py to scrollphat.pyc
installing package data to build/bdist.linux-armv6l/egg
running install_data
copying font.png -> build/bdist.linux-armv6l/egg/.
creating build/bdist.linux-armv6l/egg/EGG-INFO
copying scrollphat.egg-info/PKG-INFO -> build/bdist.linux-armv6l/egg/EGG-INFO
copying scrollphat.egg-info/SOURCES.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
copying scrollphat.egg-info/dependency_links.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
copying scrollphat.egg-info/requires.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
copying scrollphat.egg-info/top_level.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
scrollphat: module references __file__
creating 'dist/scrollphat-0.0.2-py2.7.egg' and adding 'build/bdist.linux-armv6l/egg' to it
removing 'build/bdist.linux-armv6l/egg' (and everything under it)
Processing scrollphat-0.0.2-py2.7.egg
removing '/usr/lib/python2.7/site-packages/scrollphat-0.0.2-py2.7.egg' (and everything under it)
creating /usr/lib/python2.7/site-packages/scrollphat-0.0.2-py2.7.egg
Extracting scrollphat-0.0.2-py2.7.egg to /usr/lib/python2.7/site-packages
scrollphat 0.0.2 is already the active version in easy-install.pth

Installed /usr/lib/python2.7/site-packages/scrollphat-0.0.2-py2.7.egg
Processing dependencies for scrollphat==0.0.2
Searching for pillow
Reading https://pypi.python.org/simple/pillow/
Best match: Pillow 3.0.0
Downloading https://pypi.python.org/packages/source/P/Pillow/Pillow-3.0.0.zip#md5=dd81f6cc3f3a5e5fe72f0f1d936339c3
Processing Pillow-3.0.0.zip
Writing /tmp/easy_install-5exqdt/Pillow-3.0.0/setup.cfg
Running Pillow-3.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5exqdt/Pillow-3.0.0/egg-dist-tmp-ooV7sO
Single threaded build, not installing mp_compile:1 processes
Traceback (most recent call last):
  File "./setup.py", line 56, in <module>
    'smbus'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 390, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 620, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 671, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 719, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1091, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1103, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 639, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 669, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 853, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1081, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1067, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 139, in resume
    compat.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-5exqdt/Pillow-3.0.0/setup.py", line 767, in <module>
    
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 160, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 146, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 10, in run
    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/tmp/easy_install-5exqdt/Pillow-3.0.0/setup.py", line 515, in build_extensions
    
ValueError: --enable-jpeg requested but jpeg not found, aborting.
```

**Comment by Gadgetoid** [comment]
I'm guessing this will be pip's horrible dependency management striking again. I'll have to remove `pillow` from the package altogether.

Try our one-liner:

```
curl get.pimoroni.com/scrollphat | bash
```

**Comment by alexellis** [comment]
Thanks for the reply. I read over the bash script, and I'm pretty sure it won't work with Arch Linux. I did go through some pain and got it working after installing everything needed manually. I'd suggest adding instructions for Arch as an appendix. 

Seeing as this is mainly using SMBus... and Python libraries there doesn't seem to be any hard dependency on Raspbian itself.

```
if [[ "" == $IS_RASPBIAN ]]; then
    warning "Warning!"
    echo "Please only run this script on Raspbian on your Raspberry Pi"
    exit 1;
fi
```

**Comment by Gadgetoid** [comment]
Honestly, I just can't spare the time to test and document install on Arch Linux at the moment, but I'd be happy to include any instructions submitted as a PR. When it comes to OS support it's easier to just draw the line dead at "Raspbian" and assume anyone using anything else has the requisite skills to figure it out. It's not ideal, and is something I'd love to change in future ( since I tend to enjoy the challenge and like keeping up with other OSes ), but as always time is my enemy!

I should probably re-evaluate the Raspbian checks, but I wanted to make sure the script wasn't easy to run anywhere it could cause untold destruction or fail in creative and unexpected ways.

**Comment by Gadgetoid** [comment]
I've totally dropped the requirement for PIL in the latest GitHub version, it should now work for you!

**Comment by alexellis** [comment]
@Gadgetoid I will have to try this on a freshly set up SD card, then I will let you know how it goes with Arch Linux.

It may still require some modules to be installed via pip or easy_install as I remember - this was 8th December when I tried last.

**Comment by alexellis** [comment]
@Gadgetoid I still haven't done instructions for Arch Linux. Will close issue.
